doctrine:
    dbal: { connections: { default: { host: localhost, port: 3306, user: root, password: F1nP@ss!255, dbname: pimcore, mapping_types: { enum: string, bit: boolean }, server_version: 8.0.41-0ubuntu0.22.04.1 } } }
