<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSXx9Lmk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSXx9Lmk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSXx9Lmk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSXx9Lmk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSXx9Lmk\App_KernelDevDebugContainer([
    'container.build_hash' => 'SXx9Lmk',
    'container.build_id' => 'b985ad22',
    'container.build_time' => 1745364091,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSXx9Lmk');
